### ISSUE TITLE
Minor issue: superfluous dot

### ISSUE THREAD

**Issue by Kirill-Johnson** [w3c/html-media-capture#25]
I recently [translated](http://topolyan.com/w3c/html_media_capture_ru.html) the HTML Media Capture specification, and noticed a couple of issues in the document.

Although they are small, I thought that it's still worth reporting about them.

Firstly, two dots after the "Please send them to public-device-apis@w3.org (subscribe, archives) or file an issue on GitHub":
![github_two_dots](https://user-images.githubusercontent.com/10576847/36483712-8e8c6898-171f-11e8-8c88-3f60e4121c18.png)

The current repository doesn't contain this sentence, but the actual document on the W3C site does.

In general, I think it's one minute fix.

**Comment by anssiko** [comment]
First, thanks for the translation!

We’ll look into the typo fix. Due to process-related reasons even the smallest change to a doc that has reached Rec is rather laborous. @xfq to look into the fix.

**Comment by xfq** [comment]
Here's how to update the Recommendation with only editorial changes: https://www.w3.org/Guide/transitions?profile=REC&rec=editorial

However, I would like to label this as errata for now instead of sending the transition/publication request for an Edited Recommendation, and wait until we have more important issues.

**Comment by anssiko** [comment]
@xfq agreed, thanks for explaining the process of updating Rec.

**Comment by xfq** [comment]
Removing the `errata` label, since this issue was fixed by [in-place modification](https://www.w3.org/2003/01/republishing/).
