### ISSUE TITLE
Obsolete link?

### ISSUE THREAD

**Issue by Kirill-Johnson** [w3c/html-media-capture#26]
Another one minor issue, that I would consider, is the link to superseded document.

"This document is governed by the 1 March 2017 W3C Process Document."

The referred document is superseded and suggests go to the version of the document from 1 February 2018. Perhaps, you could just refer to this version.

UPD. The current repository seems to already fixed this, but I was referring to the [Recommendation](https://www.w3.org/TR/html-media-capture/) on W3C site.

**Comment by anssiko** [comment]
Thanks for the report. The Recommendation was published on the same day as the W3C Process Document update, so referring to the 1 March 2017 W3C Process Document in the Rec is correct. The Process doc evolves ~annually while Recs refer to the latest Process operational at the time of a publication.
