### ISSUE TITLE
[meta] Translations tracker

### ISSUE THREAD

**Issue by anssiko** [w3c/html-media-capture#27]
Japanese: http://www.asahi-net.or.jp/~ax2s-kmtn/internet/media/REC-html-media-capture-20180201.html
Korean: https://techhtml.github.io/html-media-capture/
Russian: http://topolyan.com/w3c/html_media_capture_ru.html

Given https://lists.w3.org/Archives/Public/w3c-translators/2017JanMar/0000.html find out what is the new automated solution to surface these translations in the spec.

**Comment by Kirill-Johnson** [comment]
Hey Anssi, it's nice that you're trying to find out a new solution.

But I don't really understand why such an organization as W3C can't afford a simple database server.

As far as I understand, your previous solution was obsolete, and you did't find a new way:
"The system that has been handling the Database has continued to not age gracefully and maintenance --which was costly already months ago-- became problematic recently".

Maybe you could make this problem more public, and people would come up with something worthy?

**Comment by xfq** [comment]
The [document](https://www.w3.org/TR/html-media-capture/) was modified [in-place](https://www.w3.org/2003/01/republishing/) to include links to the translations. @anssiko, can we close this issue, or do you want to keep this issue open, to track future translations?

**Comment by xfq** [comment]
I just submitted a PR to update the document hosted on GitHub. Please see https://github.com/w3c/html-media-capture/pull/29.

**Comment by anssiko** [comment]
Thanks for the in-place edit, that works for this spec.

From @chaals I understood AB has been tasked to investigate the general issue around translations -- please drop a link to the respective AB tracker issue, if any.

**Comment by xfq** [comment]
@anssiko FYI: https://lists.w3.org/Archives/Public/w3c-translators/2018JulSep/0048.html

**Comment by xfq** [comment]
See also: https://lists.w3.org/Archives/Public/w3c-translators/2019JanMar/0020.html
