### ISSUE TITLE
The empty string is not defined as a conforming value for the capture attribute

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/html-media-capture#34]
At https://w3c.github.io/html-media-capture/#the-capture-attribute the spec states:
> The attribute's keywords are `user` and `environment`, which map to the respective states _user_ and _environment_.

…but the spec does not define the empty string as a conforming keyword.

Because the spec doesn’t define the empty string as a conforming keyword, the following example from the spec itself doesn’t conform to the actual requirements in the spec —

```html
<form action="server.cgi" method="post" enctype="multipart/form-data">
  <input type="file" name="audio" accept="audio/*" capture>
  <input type="submit" value="Upload">
</form>
```

**Comment by anssiko** [comment]
If the attribute value matches none of the given keywords, the invalid value default maps to an implementation-specific state that indicates to the implementation to act according to its default behavior. IIRC this design was for historical reasons.

**Comment by sideshowbarker** [comment]
> If the attribute value matches none of the given keywords, the invalid value default maps to an implementation-specific state that indicates to the implementation to act according to its default behavior.

That applies to the action of the implementation, which is orthogonal to the document-conformance requirements (authoring-conformance requirements). The issue is that the document-conformance requirements explicitly state that `user` and `environment` are valid keywords, but don’t explicitly state that the empty string is a valid keyword.

For the empty string to be considered a valid value that documents and authors are allowed to use, it must be explicitly included in the same spec sentence that begins with *The attribute's keywords are `user` and `environment`*.

Compare to https://html.spec.whatwg.org/multipage/interaction.html#contenteditable:

> The `contenteditable` content attribute is an enumerated attribute whose keywords are the empty string, `true`, and `false`.

Or compare to https://html.spec.whatwg.org/multipage/media.html#attr-media-preload, which states that for  the`preload` attribute, *The following table lists the keywords and states for the attribute*, and then lists `none`, `metadata`, and `auto`, followed by this statement:

> The empty string is also a valid keyword, and maps to the Automatic state.

**Comment by anssiko** [comment]
@sideshowbarker thanks for the clarification, PTAL https://github.com/w3c/html-media-capture/pull/35
