### ISSUE TITLE
Update test suite

### ISSUE THREAD

**Issue by anssiko** [w3c/html-media-capture#7]
@Honry (or @zqzhang, test suite owner) Could you help update the test suite to match the recent changes that addressed issue #4.

See the [HTML diff][1] comparing the spec just [before][2] and [after][3] the following changes:
https://github.com/w3c/html-media-capture/commit/0a3564e7601c8085581293cc5adb9ee2292440ce
https://github.com/w3c/html-media-capture/commit/ccd71a186fb08c8a2193556474aa955bdf11fac7
https://github.com/w3c/html-media-capture/commit/991921e6821deac95fba90b971306e040149bd30

Latest Editor's Draft:
https://w3c.github.io/html-media-capture/

Test suite (matches [CR](https://www.w3.org/TR/html-media-capture/) currently):
http://w3c-test.org/html-media-capture/
https://github.com/w3c/web-platform-tests/tree/master/html-media-capture

I think we need at least the following tests updated/added:
- [x] update IDL harness tests
- [x] [`user`](https://w3c.github.io/html-media-capture/#dom-capturefacingmode-user)
- [x] [`environment`](https://w3c.github.io/html-media-capture/#dom-capturefacingmode-environment)
- [x] invalid value default
- [x] missing value default

@riju is working to update the Chromium implementation to match.

[1]: http://services.w3.org/htmldiff?doc1=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%253A%252F%252Frawgit.com%252Fw3c%252Fhtml-media-capture%252F400759c94abd4641f8996e4f47c76dc8b1063e8e%252Findex.html%253FspecStatus%253DED%253BshortName%253Dhtml-media-capture&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%253A%252F%252Frawgit.com%252Fw3c%252Fhtml-media-capture%252Fgh-pages%252Findex.html%253FspecStatus%253DED%253BshortName%253Dhtml-media-capture

[2]: https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawgit.com%2Fw3c%2Fhtml-media-capture%2F400759c94abd4641f8996e4f47c76dc8b1063e8e%2Findex.html%3FspecStatus%3DED%3BshortName%3Dhtml-media-capture

[3]: https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawgit.com%2Fw3c%2Fhtml-media-capture%2Fgh-pages%2Findex.html%3FspecStatus%3DED%3BshortName%3Dhtml-media-capture

**Comment by Honry** [comment]
Yes, I can help update the test suite.

**Comment by Honry** [comment]
@anssiko or @riju, could you please inform me once the update in Chromium implementation is done? Thus I can verify the tests.

**Comment by riju** [comment]
@Honry : sure, will update soon.

**Comment by anssiko** [comment]
WIP Chromium implementation: https://crbug.com/698853

**Comment by anssiko** [comment]
@Honry, HTML Media Capture implementation (based on the [latest Editor's Draft][1]) now ships in [Safari 10.1 / iOS 10.3][2]. Could you update the test suite and create a test report ([example][3]) for it with iOS Safari results?

@riju, could you update the Chromium implementation so that the updated IDL tests will pass on Chromium? Even with the [known Android API limitation][4], such an implementation would be spec conformant given the [preferred facing mode][5] is a hint and the spec gives leeway for implementations to fall back to the implementation-specific default facing mode, if the user agent is unable to support the preferred facing mode.

[1]: https://w3c.github.io/html-media-capture/
[2]: https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_1.html#//apple_ref/doc/uid/TP40014305-CH12-DontLinkElementID_51
[3]: http://w3c.github.io/test-results/vibration/20141118.html
[4]: https://bugs.chromium.org/p/chromium/issues/detail?id=698853#c11
[5]: https://w3c.github.io/html-media-capture/#dfn-preferred-facing-mode

**Comment by Honry** [comment]
@anssiko, sure. I will update soon.

**Comment by riju** [comment]
@anssiko, yes will update my CL soon.

**Comment by anssiko** [comment]
@Honry @riju, thanks!

@dontcallmedom, given good progress on the implementation front, I think we should try to publish a revised Candidate Recommendation soon. Could you help obtain the [required][1] Director's approval to publish a CR revision?

[1]: https://www.w3.org/2015/Process-20150901/#revised-cr

**Comment by dontcallmedom** [comment]
@anssiko before doing the transition request, we need to confirm there is WG consensus for the updated CR, and check whether we need reviews from specific groups on the said change. Maybe start a thread on the mailing list?

**Comment by anssiko** [comment]
@dontcallmedom sent a mail to the list: https://lists.w3.org/Archives/Public/public-device-apis/2017Mar/0022.html

**Comment by Honry** [comment]
@anssiko, I just updated the tests, could you help review it? I will create a test report with iOS Safari once the tests are merged.

**Comment by anssiko** [comment]
@Honry the updated tests look good to me, thanks!

**Comment by Honry** [comment]
@anssiko, the test report for Safari 10.1 is ready at https://github.com/w3c/test-results/pull/89.
I capture one bug that the browser always launch camera when the capture attribute is set and the accept attribute is set to 'audio/*' or 'text/plain' (Note: bug has been reported to Apple but without open link as it is close source).
Please help review it. :)

**Comment by anssiko** [comment]
The [CfC to publish a revised CR][1] passed with no concerns so I expect us to be able to publish an updated CR shortly.

@Honry, do you think you could land https://github.com/w3c/test-results/pull/89 soon so we could link to it in from the revised CR specification?

[1]: https://lists.w3.org/Archives/Public/public-device-apis/2017Mar/0024.html

**Comment by Honry** [comment]
@anssiko, shall we wait for the test result with Chromium?

**Comment by anssiko** [comment]
We can add Chromium in a subsequent update. Please replace the duplicate column in the report with a placeholder for Chromium and merge the report.

**Comment by Honry** [comment]
Done, please check. :)

**Comment by anssiko** [comment]
@riju, could you give us an update on the Chromium implementation status?

The spec will transition to Candidate Recommendation on 04 May 2017 and it would be great to have the implementation ready by that date.

**Comment by riju** [comment]
@anssiko :  I have the chromium [CL](https://codereview.chromium.org/2735633004/) almost ready for review. Need to test a bit more. Will update this thread, when it goes in.

**Comment by anssiko** [comment]
The Chrome for Android data has been added to the test results:

http://w3c.github.io/test-results/html-media-capture/20170428.html

The implementation status wiki has been updated accordingly:

https://www.w3.org/2009/dap/wiki/ImplementationStatus

Thanks @Honry!

**Comment by anssiko** [comment]
The test suite has been updated, and we have test results. 

Closing this issue. For the latest results please refer to the [implementation report][1] linked from the spec header too.

[1]: https://www.w3.org/2009/dap/wiki/ImplementationStatus
