### ISSUE TITLE
No facing mode for microphone when capturing audio

### ISSUE THREAD

**Issue by Honry** [w3c/html-media-capture#8]
> Or alternatively, to capture audio using the device's local microphone (without preferred facing mode defined, falls back to the implementation-specific default facing mode):

This sentence is inconsistent, there's no facing mode for device's local microphone when capturing audio.

**Comment by anssiko** [comment]
Thanks for the issue. Even if the devices in the market today do not (commonly^) have multiple built-in microphones, it does not mean there wouldn't be such devices in the future. To future-proof the API, the [preferred facing mode][1] concept was specified to scale to microphones as well using the [media capture mechanism][2] abstraction.

(^Already today, one can add additional microphones via USB.)

This informative text in the said example:

>(without preferred facing mode defined, falls back to the implementation-specific default facing mode)

Maps back to this normative statement:

>The missing value default is the implementation-specific state.

I suggest no changes to the spec needed.

[1]: https://w3c.github.io/html-media-capture/#dfn-preferred-facing-mode
[2]: https://w3c.github.io/html-media-capture/#dfn-media-capture-mechanism
